/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Anotaciones.java
 *
 * Created on 16-may-2013, 13:37:33
 */
package biblioteca;

    import java.io.BufferedReader;
    import java.io.File;
    import java.io.FileNotFoundException;
    import java.io.FileReader;
    import java.io.FileWriter;
    import java.io.IOException;
    import java.io.PrintWriter;
    import java.util.logging.Level;
    import java.util.logging.Logger;

/**
 *
 * @author Administrador
 */
public class Anotaciones extends javax.swing.JFrame {

    /** Creates new form Anotaciones */
    public Anotaciones() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setTitle("Anotaciones / Recordatorios");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Añadir Anotacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver Anotaciones");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int año=jCalendar1.getCalendar().get(java.util.Calendar.YEAR);
        int mes=jCalendar1.getCalendar().get(java.util.Calendar.MONTH)+1;
        int dia=jCalendar1.getCalendar().get(java.util.Calendar.DATE);         
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            fichero = new FileWriter("src/Notas.txt",true);
        } catch (IOException ex) {
            Logger.getLogger(Anotaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        pw = new PrintWriter(fichero);
        pw.println(dia+"/"+mes+"/"+año+" "+Login.TextoUser.getText()+": "+jTextArea1.getText());
        if (null != fichero)
              try {
            fichero.close();
        } catch (IOException ex) {
            Logger.getLogger(Anotaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea1.setText("");
        javax.swing.JOptionPane.showMessageDialog(this, "Su nota ha sido guardada");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        File arch=new File ("src/Notas.txt");
        FileReader fire = null;
        try {
            fire = new FileReader (arch);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Anotaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader bure = new BufferedReader(fire);
        String linea="";
        String mensaje="";
        try {
            while((linea=bure.readLine())!=null){
                mensaje=mensaje+linea+"\n";}
        } catch (IOException ex) {
            Logger.getLogger(Anotaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(null!= fire){   
            try {
                fire.close();
            } catch (IOException ex) {
                Logger.getLogger(Anotaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jTextArea1.setText(mensaje);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButton1;
    protected javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
